### ISSUE TITLE
Jquery 3.1.1

### ISSUE THREAD

**Issue by vicwebdesign** [bcat-eu/jquery-bgswitcher#2]
bgswitcher will not work with newest jquery version 3.1.1

**Comment by godzik** [comment]
@vicwebdesign Ty for your report :O)
.load() deprecated in 3.x version.
You should change .load(fucntion(){}) -> .on('load', function(){}) in code 
or there will be update soon.

**Comment by bcat-eu** [comment]
@vicwebdesign fixed, version 2.2.1 should do it for newest jQuery

you can fetch it here or bump your npm dependency https://www.npmjs.com/package/bcat.bgswitcher

@godzik thanks!
